//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartMonkey
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Maquina
    {
        public int idMaquina { get; set; }
        [DisplayName("Modelo")]
        public string modelo { get; set; }
        [DisplayName("Processador")]
        public string processador { get; set; }
        [DisplayName("RAM")]
        public int memoriaRam { get; set; }
        [DisplayName("HD")]
        public double discoRigido { get; set; }
        [DisplayName("Delimitador CPU")]
        public Nullable<double> delimitCpu { get; set; }
        [DisplayName("Delimitador RAM")]
        public Nullable<double> delimitRam { get; set; }
        [DisplayName("Delimitador HD")]
        public Nullable<double> delimitHd { get; set; }
        [DisplayName("Instituição")]
        public Nullable<int> idInstituicao { get; set; }
        [DisplayName("Instituição")]
        public virtual Instituicao Instituicao { get; set; }
    }
}
