//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartMonkey
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Usuario
    {
        public int idUsuario { get; set; }
        [DisplayName("Nome")]
        public string nome { get; set; }
        [DisplayName("CPF")]
        public string cpf { get; set; }
        [DisplayName("E-mail")]
        public string email { get; set; }
        public string login { get; set; }
        public string senha { get; set; }
        [DisplayName("Cargo")]
        public string cargo { get; set; }
        [DisplayName("Ativo")]
        public Nullable<bool> ativo { get; set; }
    }
}
